[project]
name = "rqlalchemy"
version = "0.6.0"
description = "Resource Query Language for SQLAlchemy"
authors = [{ name = "Pedro Werneck", email = "pjwerneck@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
keywords = ["sqlachemy", "sql", "rql", "querying", "httpapi"]
dependencies = [
    "pyrql>=0.7.11",
    "sqlalchemy>=2.0",
]

[project.urls]
Repository = "https://github.com/pjwerneck/rqlalchemy"
Homepage = "https://github.com/pjwerneck/rqlalchemy"

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-coverage>=0.0",
    "ruff>=0.9.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rqlalchemy"]

[tool.ruff]
exclude = [".git", ".venv"]
line-length = 99
target-version = "py38"
preview = false

[tool.ruff.lint]
select = [
    "A",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "DTZ",
    "E",
    "F",
    "FURB",
    "G",
    "I",
    "ICN",
    "INT",
    "ISC",
    "LOG",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLOT",
    "T20",
    "TC",
    "TD",
    "TID",
    "TRY",
    "UP",
    "W",
]

ignore = [
  "TRY003",
  "UP007",
  "PLR2004",
  "S101",

]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.isort]
force-single-line = true

[tool.pytest.ini_options]
pythonpath = [
  "."
]
